CREATE DATABASE MRRRDATABASE;

USE MRRRDATABASE;


--PERMISOS DE USUARIO PARA ACCESO A LA BD
--CREATE LOGIN Administrador WITH PASSWORD='esnupi988';
--CREATE USER Administrador FOR LOGIN Administrador;



CREATE TABLE ORGANIZACION(
	id_org INTEGER IDENTITY(1,1) PRIMARY KEY,
	nom_com_org VARCHAR(100) NOT NULL,
	nom_legal_org VARCHAR(150) UNIQUE NOT NULL,
	tipo_org VARCHAR(50) NOT NULL,
	rubro VARCHAR(100) NOT NULL,
	cif VARCHAR(30) UNIQUE NOT NULL,
	correo_org VARCHAR(100) UNIQUE NOT NULL,
	telf_org VARCHAR(20) UNIQUE NOT NULL,
	dir_org VARCHAR(200) NOT NULL,
	fecha_registro_org DATE NOT NULL,
	sitio_web VARCHAR(150),
	logo_org VARBINARY(MAX) UNIQUE
);


CREATE TABLE ROL(
	cod_rol INTEGER IDENTITY(1,1) PRIMARY KEY,
	nom_rol VARCHAR(50),
	descr_rol VARCHAR(200) 
);


CREATE TABLE PROMOCION(
	cod_prom INTEGER IDENTITY(1,1) PRIMARY KEY,
	titulo_prom VARCHAR(100) UNIQUE NOT NULL,
	fecha_ini_prom DATE NOT NULL,
	duracion_prom INTEGER NOT NULL,
	fecha_fin_prom DATE NOT NULL,
	descr_prom VARCHAR(300) NOT NULL,
	banner_prom VARBINARY(MAX),
	descuento_prom DECIMAL(5,2) NOT NULL
);

